// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	jwt "github.com/golang-jwt/jwt/v5"

	mock "github.com/stretchr/testify/mock"
)

// JWTGenerator is an autogenerated mock type for the JWTGenerator type
type JWTGenerator struct {
	mock.Mock
}

// GenerateToken provides a mock function with given fields: claims
func (_m *JWTGenerator) GenerateToken(claims jwt.Claims) (string, error) {
	ret := _m.Called(claims)

	if len(ret) == 0 {
		panic("no return value specified for GenerateToken")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(jwt.Claims) (string, error)); ok {
		return rf(claims)
	}
	if rf, ok := ret.Get(0).(func(jwt.Claims) string); ok {
		r0 = rf(claims)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(jwt.Claims) error); ok {
		r1 = rf(claims)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewJWTGenerator creates a new instance of JWTGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewJWTGenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *JWTGenerator {
	mock := &JWTGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
