services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
  

  postgres:
    image: postgres:alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=bookmark_service
    volumes:
      - ./pgdata:/var/lib/postgresql/data