// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// UrlStorage is an autogenerated mock type for the UrlStorage type
type UrlStorage struct {
	mock.Mock
}

// GetURL provides a mock function with given fields: ctx, id
func (_m *UrlStorage) GetURL(ctx context.Context, id string) (string, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetURL")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StoreURL provides a mock function with given fields: ctx, code, url, expireIn
func (_m *UrlStorage) StoreURL(ctx context.Context, code string, url string, expireIn int) error {
	ret := _m.Called(ctx, code, url, expireIn)

	if len(ret) == 0 {
		panic("no return value specified for StoreURL")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int) error); ok {
		r0 = rf(ctx, code, url, expireIn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewUrlStorage creates a new instance of UrlStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUrlStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *UrlStorage {
	mock := &UrlStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
