// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Encoder is an autogenerated mock type for the Encoder type
type Encoder struct {
	mock.Mock
}

// DecodeStringToInt64 provides a mock function with given fields: s
func (_m *Encoder) DecodeStringToInt64(s string) (int64, error) {
	ret := _m.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for DecodeStringToInt64")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (int64, error)); ok {
		return rf(s)
	}
	if rf, ok := ret.Get(0).(func(string) int64); ok {
		r0 = rf(s)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(s)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EncodeInt64ToString provides a mock function with given fields: num
func (_m *Encoder) EncodeInt64ToString(num int64) (string, error) {
	ret := _m.Called(num)

	if len(ret) == 0 {
		panic("no return value specified for EncodeInt64ToString")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(int64) (string, error)); ok {
		return rf(num)
	}
	if rf, ok := ret.Get(0).(func(int64) string); ok {
		r0 = rf(num)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(num)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewEncoder creates a new instance of Encoder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEncoder(t interface {
	mock.TestingT
	Cleanup(func())
}) *Encoder {
	mock := &Encoder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
