basePath: /
definitions:
  handler.healthCheckResponse:
    properties:
      instance_id:
        type: string
      message:
        type: string
      service_name:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: author@gmail.com
    name: API Support
    url: http://www.example.com/support
  description: This is the API documentation for the Bookmark Management service.
  title: Bookmark Management API
  version: "1.0"
paths:
  /generate-password:
    get:
      description: Generates a cryptographically secure random password of fixed length.
      produces:
      - text/plain
      responses:
        "200":
          description: w7h3Q9FeXskn
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Generate a random password
      tags:
      - password
  /health-check:
    get:
      description: Performs a health check and returns the service status.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.healthCheckResponse'
      summary: Health Check
      tags:
      - health
schemes:
- http
swagger: "2.0"
